logger:
    # error: 0
    # warn: 1
    # info: 2
    # verbose: 3
    # debug: 4
    # silly: 5
    # allow individual modules to set level from method logger.getLogger()
    allowModuleOverride: false
    file: /var/log/error.log
    fileLogging: true
    fileLoggingLevel: error
    consoleLogging: true
    consoleLoggingLevel: debug # overall logging level
app:
    consoleLoggingLevel: warn
cache:
    id: cache.json
tasks:
    welcome:
        pauseDurationMs: 1000 # milliseconds
    read:
        intervalMs: 1000 # milliseconds (should not be faster than 800ms, the slowest sensor integration time)
    # settings:
        # lcdInterval: 250 # milliseconds
        # exposure:
            # increments: 25000 # uv accumulated per min
            # max: 50000000
            # min: 100000
    # exposure:
        # lcdInterval: 500 # milliseconds
        # buzzIncrement: 50000 # uv accumulated per min
        # maxMissingUVReadings: 10 # will stop exposure if xx UV readings are missed
peripherals:
    lcdScreen:
        config:
            consoleLoggingLevel: warn
            address: 0x20
    # giopReset:
        # config:
            # consoleLoggingLevel: warn
    # buttons:
        # config:
            # consoleLoggingLevel: warn
            # debounceMs: 500 # milliseconds
            # holdDelay: 500 # milliseconds
            # holdRepeat: 100 # milliseconds
        # buttons:
            # exposureUp:
                # gpioPin: 27
            # exposureDown:
                # gpioPin: 22
            # exposureStart:
                # gpioPin: 17
            # exposureStop:
                # gpioPin: 4
    # leds:
        # config:
            # consoleLoggingLevel: warn
        # leds:
            # ledGreen:
                # gpioPin: 16
            # ledRed:
                # gpioPin: 21
            # ledYellow:
                # gpioPin: 20
    # buzzer:
        # config:
            # consoleLoggingLevel: warn
            # gpioPin: 26
    # relays:
        # config:
            # consoleLoggingLevel: warn
        # relays:
            # relayA:
                # gpioPin: 14
            # relayB:
                # gpioPin: 15
    uvSensor:
        config:
            consoleLoggingLevel: warn
            logReadingsToConsole: true
            dynamicRangeHigh: false # HD mode increases the bit depth, but requires manual coefficients calibration
            integrationTimesMs: [50, 100, 200, 400, 800] # (50ms is default)
            integrationTimeInitialIndex: 4 # 0-4
            reconfigureSensorIntervalMs: 1000 # Should be greater than highest possible integration time
            bus:
                number: 1
                address: 0x10